# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "main"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "4.3.x"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "4.2.x"
    schedule:
      interval: "weekly"
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: main
    ignore:
      # IDE specific dependency
      - dependency-name: "org.eclipse.m2e:lifecycle-mapping"
      # JRuby updates are causing docs generation to fail
      - dependency-name: "org.jruby:jruby-complete"  
      # only upgrade by minor or patch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: 4.3.x
    ignore:
      # IDE specific dependency
      - dependency-name: "org.eclipse.m2e:lifecycle-mapping"
      # JRuby updates are causing docs generation to fail
      - dependency-name: "org.jruby:jruby-complete"  
      # only upgrade by minor or patch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    target-branch: 4.2.x
    ignore:
      # IDE specific dependency
      - dependency-name: "org.eclipse.m2e:lifecycle-mapping"
      # JRuby updates are causing docs generation to fail
      - dependency-name: "org.jruby:jruby-complete"
      # only upgrade by minor or patch
      - dependency-name: "*"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
  - package-ecosystem: npm
    target-branch: docs-build
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: main
    directory: /docs
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: 4.3.x
    directory: /docs
    schedule:
      interval: weekly
  - package-ecosystem: npm
    target-branch: 4.2.x
    directory: /docs
    schedule:
      interval: weekly
